from __future__ import annotations
from typing import Protocol, Any


class RunnerPort(Protocol):
    def status(self) -> dict: ...
    def list_projects(self) -> list[str]: ...
    def start_project(self, name: str) -> None: ...
    def stop_project(self) -> None: ...
    def capture_now(self) -> dict: ...
    def shutdown(self) -> None: ...